# Welcome to Serverless!
service: test-serverless-lambda

provider:
  name: aws
  runtime: nodejs12.x

# you can overwrite defaults here
 stage: dev
 region: us-east-1

functions:
  hello:
    handler: handler.randomNumberGenerator
